- FlashLFQ/ProteinQuantificationEngine.cpp
testing the pull-request mechanism on the new repo
> ProteinQuantificationEngine.cpp: minor change

- .gitignore
- Test/runtest.sh
to create a soft-link for elements.dat.
> runtest.sh: update the script in the main Test directory

- Makefile
- Test/runcheck.sh
> initial setup for ci-testing

- Test/runcheck.sh
> update the make-check script

- Test/DatabaseTests/TestDatabaseLoaders.cpp
Signed-off-by: Shane <dogunbound5@gmail.com>
> TestDatabaseLoader.cpp fixing segfault

- Proteomics/ProteolyticDigestion/PeptideWithSetModifications.h
- include/Sort.h
minor fixes required to make a test case in MetaMorpheus/Test/XLTest.cpp pass.
> MetaMorpheus/XLTest: fixes to make a testcase pass

- include/Math.h
> Math.h: handle empty vector correctly by returning NaN

- Proteomics/Fragmentation/CompactPeptideBase.cpp
- Proteomics/Fragmentation/CompactPeptideBase.h
- Proteomics/ProteolyticDigestion/PeptideWithSetModifications.cpp
to correctly represent modifications.
> PeptideWithSetModifications.cpp: fix in the String generation function

- MassSpectrometry/MsDataScan.cpp
- MassSpectrometry/MzSpectra/MzSpectrum.cpp
- MassSpectrometry/MzSpectra/MzSpectrum.h
- Proteomics/AminoAcidPolymer/Peptide.cpp
- Proteomics/ProteolyticDigestion/Protease.cpp
- Proteomics/ProteolyticDigestion/Protease.h
- Proteomics/ProteolyticDigestion/ProteinDigestion.cpp
> more performance tuning.

- MassSpectrometry/MzSpectra/MzSpectrum.cpp
- Proteomics/Modifications/Modification.cpp
- Proteomics/ProteolyticDigestion/PeptideWithSetModifications.cpp
- include/Search.h
> another round of performance tuning.

- benchmarks/Makefile
- benchmarks/Mgf-Benchmark.cpp
> add an mgf file read benchmark

- MassSpectrometry/MzSpectra/MzSpectrum.cpp
- MzLibUtil/MzRange.cpp
- MzLibUtil/MzRange.h
- Test/TestSpectra.cpp
- include/Assert.h
- include/Math.h
fix the final, mostly minor items to make all tests in TestSpectra.cpp pass.
> TestSpectra.cpp: make all tests pass now

- Test/TestPeptideWithSetMods.cpp
to match the output of the other tests.
> TestPeptideWithSetMods.cpp: formating update

- configure
- configure.ac
> typo in the configure.ac script/

- MassSpectrometry/MsDataScan.h
- MassSpectrometry/SummedMsDataFile.h
- Proteomics/AminoAcidPolymer/AminoAcidPolymer.cpp
- Proteomics/AminoAcidPolymer/AminoAcidPolymer.h
- Proteomics/AminoAcidPolymer/Peptide.h
- Test/TestPeptides.cpp
- benchmarks/Benchmark.cpp
- benchmarks/Benchmarks.cs
- include/BitConverter.h
proprely delete memory in the destructor.
> mzlib: first cut on the some memory cleanups

- Proteomics/Fragmentation/MatchedFragmentIon.cpp
- Proteomics/Fragmentation/MatchedFragmentIon.h
- Proteomics/Fragmentation/Product.cpp
- Proteomics/Fragmentation/Product.h
- Proteomics/Protein/Protein.cpp
- Proteomics/ProteolyticDigestion/PeptideWithSetModifications.cpp
- Proteomics/ProteolyticDigestion/PeptideWithSetModifications.h
> mzlib: part 2 of cleaning up memory leaks

- Chemistry/IsotopicDistribution.cpp
- Test/TestIsolation.cpp
- Test/TestIsolation.h
we are hopefully now generating the correct list of masses and intensities in MzSpectrum.
Also, added some more testcases.
> IsotopicDistribution.cpp: fix sort operation

- Mgf/Mgf.cpp
> some cleanup in Mgf.cpp

- Proteomics/Fragmentation/MatchedFragmentIon.cpp
- Proteomics/Fragmentation/MatchedFragmentIon.h
- Proteomics/ProteolyticDigestion/PeptideWithSetModifications.cpp
- Proteomics/ProteolyticDigestion/PeptideWithSetModifications.h
- Test/TestSerialization.cpp
- include/BinaryPack.h
> revamp Serialization to use binary format.

- include/BinaryPack.h
> BinaryPack.h: add missing header file

- MassSpectrometry/MsDataFile.cpp
- MassSpectrometry/MsDataFile.h
Signed-off-by: nimelica <melaht2016@icloud.com>
> added new function name GetMsScansSubset

- MassSpectrometry/MsDataFile.cpp
to access the correct index. Also, add back the GetMsScansInIndexRange
> MsDataFile: minor fixes
